# Generated by Django 4.0 on 2021-12-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appointment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
    ]
